### ISSUE TITLE
`Command failed: git merge-base origin/0 HEAD` when running tagged builds

### ISSUE THREAD

**Issue by pedroyan** [nrwl/nx-orb#41]
## Orb version:
1.6.0

## What happened:

When running tagged jobs, the `set-shas` functionality isn't able to properly resolve the latest successful job and outputs the following:

```
fatal: Not a valid object name origin/0
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: git merge-base origin/0 HEAD
fatal: Not a valid object name origin/0

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at /home/circleci/project/index.js:19:16
    at Object.<anonymous> (/home/circleci/project/index.js:53:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 128,
  signal: null,
  output: [ null, '', 'fatal: Not a valid object name origin/0\n' ],
  pid: 354,
  stdout: '',
  stderr: 'fatal: Not a valid object name origin/0\n'
}

Base SHA


Head SHA
a2fba2d819a99575b9b3ef5c13e5ec8b5d92fed2


NX_BASE and NX_HEAD environment variables have been set for the current Job
CircleCI received exit code 0
```

## Expected behavior:

- `Base SHA` is resolved to the latest passing build

### Repro config.yml
```yml
version: 2.1

commands:
  install-packages:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

orbs:
  # Official NX Orb: https://github.com/nrwl/nx-orb
  nx: nrwl/nx@1.6.0

jobs:
  workflow-experiment:
    docker:
      - image: cimg/node:16.17

    steps:
      - checkout
      - install-packages

      - nx/set-shas:
          skip-branch-filter: true
          workflow-name: prod-deployment

      - run:
          name: Echo SHAs
          command: echo "base=$NX_BASE   head=$NX_HEAD"

# Tag filtering anchor
filters: &tagFilter
  tags:
    only:  /^v[0-9]+(\.[0-9]+)*$/ # only act on version tags

workflows:
  version: 2

  prod-deployment:
    jobs:
      - workflow-experiment:
          filters: *tagFilter

```

### Build environment variables
```
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-6323bd61a4378057e83df117-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=
  CIRCLE_BUILD_NUM=508
  CIRCLE_BUILD_URL=[REDACTED]
  CIRCLE_JOB=Deploying to Prod
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_PROJECT_REPONAME=[REDACTED]
  CIRCLE_PROJECT_USERNAME=[REDACTED]
  CIRCLE_REPOSITORY_URL=[REDACTED]
  CIRCLE_SHA1=49244e3e111f667cf626c794a59efc05c7377eb6
  CIRCLE_SHELL_ENV=/tmp/.bash_env-6323bd61a4378057e83df117-0-build
  CIRCLE_TAG=v0.0.8
  CIRCLE_USERNAME=[REDACTED]
  CIRCLE_WORKFLOW_ID=9d7d5ff0-e8ee-4adc-950e-acbb3bfcca9d
  CIRCLE_WORKFLOW_JOB_ID=a781656d-18b7-4f6b-affc-c020cd46631f
  CIRCLE_WORKFLOW_WORKSPACE_ID=9d7d5ff0-e8ee-4adc-950e-acbb3bfcca9d
  CIRCLE_WORKING_DIRECTORY=~/project
```
