### ISSUE TITLE
`main-branch-name: $CIRCLE_BRANCH` always returns the same value for both the `Base SHA` and `Head SHA`

### ISSUE THREAD

**Issue by jackblackevo** [nrwl/nx-orb#48]
## Orb version:

nrwl/nx@1.6.1

## What happened:

I pass `$CIRCLE_BRANCH` to the `nx/set-shas` command, but I always receive the same value for both the `Base SHA` and the `Head SHA`.

Output of **Derives SHAs for base and head for use in `nx affected` commands**:

```
Commit: 3f835dfe18a35cfc74bf4a2773d366f09c298f8b
Base SHA
3f835dfe18a35cfc74bf4a2773d366f09c298f8b

Head SHA
3f835dfe18a35cfc74bf4a2773d366f09c298f8b


NX_BASE and NX_HEAD environment variables have been set for the current Job
```

## Expected behavior:

The `Base SHA` should represent the last successful workflow run on 'origin/feature-branch'.

## Additional Information:

.circleci/config.yml:

```yaml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  nx: nrwl/nx@1.6.1

jobs:
  affected_test:
    executor:
      name: node/default
      tag: '18.16.0'
    steps:
      - checkout
      - node/install-packages
      - nx/set-shas:
          main-branch-name: $CIRCLE_BRANCH # <- Use $CIRCLE_BRANCH built-in environment variables
      - run: npx nx affected -t test --base=$NX_BASE --head=$NX_HEAD

workflows:
  lint_and_test_build:
    jobs:
      - affected_test:
          context:
            - circleci # <- Access CircleCI Context to get $CIRCLE_API_TOKEN
```

**Comment by jackblackevo** [comment]
I discovered the compiled CircleCI config:

```yaml
environment:
  PARAM_ALLOW_ON_HOLD: false
  PARAM_ERROR_ON_NO_SUCCESSFUL_WORKFLOW: false
  PARAM_MAIN_BRANCH: $CIRCLE_BRANCH # <- The string $CIRCLE_BRANCH itself, not its value
```

So the [`if...else` condition](https://github.com/nrwl/nx-orb/blob/ff01c917b8fe574804c518447b15d927aa453c8e/src/scripts/find-successful-workflow.js#LL18C17-L18C17) in `find-successful-workflow.js` is actually:

```javascript
if ('feature-branch' !== '$CIRCLE_BRANCH') {
  // ...
} else {
  // ...
}
```

Finally, the [`execSync`](https://github.com/nrwl/nx-orb/blob/ff01c917b8fe574804c518447b15d927aa453c8e/src/scripts/find-successful-workflow.js#LL19C5-L19C96) in `find-successful-workflow.js` actually executes the following command in bash:

```shell
git merge-base origin/$CIRCLE_BRANCH HEAD
```

That is the cause of this problem.
