### ISSUE TITLE
Project Not Found issue with separate workflows

### ISSUE THREAD

**Issue by kenneth-howe** [nrwl/nx-orb#5]
## What happened:

We have two workflows: one for opened PRs, and one for post-merge. For the PR workflow, the SHAs get set with no issues. However, post-merge and in the main workflow, the Base SHA never gets set, and instead we get this error:

`{:message "Project not found"}`

We see an issue from August related to private repos (#2), but it seems to be a different issue given it works for one of our jobs/workflows but not the other.

## Expected behavior:

The orb is able to set the Base SHA for all of our jobs/workflows.

## Additional Information:

For now, both workflows use the exact same steps, as seen below. Note that I've redacted our tokens, but they are the same value in both jobs.

```
main:
    docker:
      - image: circleci/node:12
        environment:
          CIRCLE_TOKEN: <redacted>
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: token placement
          command: 'echo "//registry.npmjs.org/:_authToken=<redacted> > ~/.npmrc'
      - run: cd 1eq && npm ci
      - nx/set-shas
      - run: cd 1eq && npx nx affected --target=deps --parallel --max-parallel=3
      - run: cd 1eq && npx nx affected --target=build --parallel --max-parallel=3
  pr:
    docker:
      - image: circleci/node:12
        environment:
          CIRCLE_TOKEN:<redacted>
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: token placement
          command: 'echo "//registry.npmjs.org/:_authToken=<redacted>" > ~/.npmrc'
      - run: cd 1eq && npm ci
      - nx/set-shas
      - run: cd 1eq && npx nx affected --target=deps --parallel --max-parallel=3
      - run: cd 1eq && npx nx affected --target=build --parallel --max-parallel=3
```

Our workflows are defined as:

```
workflows:
  build:
    jobs:
      - main:
          context: AWS
          filters:
            branches:
              only: main
      - pr:
          context: AWS
          filters:
            branches:
              ignore: main
```

I've joined the @nrwl/community on Slack, so please feel free to reach out.
