### ISSUE TITLE
Unexpected error with non-existing successfull builds

### ISSUE THREAD

**Issue by DavidPLamas** [nrwl/nx-orb#6]
## Orb version:
1.1.2

## What happened:
I set up the circleci configuration file for the first time using the guidelines in the [documentation ](https://circleci.com/developer/orbs/orb/nrwl/nx) but it is not working as expected. It looks like the step nx/set-shas has an error and the rest of the workflow does not proceed the way it was supposed to be.

## Expected behavior:
The build should finish with success

## Additional Information:
Here is my circleci configuration file:

```
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  nx: nrwl/nx@1.1.2

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers
    steps:
      # ...CI steps like checkout, install...
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run:
          command: yarn nx affected --target=build --base=$NX_BASE --parallel --max-parallel=3
          name: Run Builds
      - run:
          command: yarn nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows: 
  version: 2
  build:
    jobs:
      - build
```

Here is the output from circleci:
![image](https://user-images.githubusercontent.com/8373746/140433620-dbc79c27-5098-4461-aeba-dddca204e72b.png)

**Comment by DavidPLamas** [comment]
The problem was fixed by introducing the CIRCLE_API_TOKEN environment variable, which is in fact documented in the Readme file of this repository. You should probably update [CircleCI official documentation](https://circleci.com/developer/orbs/orb/nrwl/nx) page with this feature as well.

**Comment by cdierkens** [comment]
@DavidPLamas I have CIRCLE_API_TOKEN set in my project environment variables but I'm still getting the error. Is there something I need to do to make CIRCLE_API_TOKEN available to the orb?

**Comment by DavidPLamas** [comment]
> @DavidPLamas I have `CIRCLE_API_TOKEN` set in my project environment variables but I'm still getting the error. Is there something I need to do to make `CIRCLE_API_TOKEN` available to the orb?

Yes, there is. Go to your project settings in Circle CI and add that new environmental variable.

**Comment by cdierkens** [comment]
>  I have `CIRCLE_API_TOKEN` set in my project environment variables but I'm still getting the error.

Something else is afoot. I already have that set.

**Comment by DavidPLamas** [comment]
> > I have `CIRCLE_API_TOKEN` set in my project environment variables but I'm still getting the error.
> 
> Something else is afoot. I already have that set.

I haven't worked on that project for about a month, so something might have changed meanwhile... 
This is my current pipeline:

```
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  nx: nrwl/nx@1.1.2

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers
    steps:
      # ...CI steps like checkout, install...
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run:
          command: yarn affected:build --base=$NX_BASE --parallel --max-parallel=3
          name: Run Builds
      # - run:
      #     command: yarn nx affected --target=test --base=$NX_BASE
      #     name: Run Unit Tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows: 
  version: 2
  build:
    jobs:
      - build
```
