### ISSUE TITLE
CircleCI set-shas: Project not found

### ISSUE THREAD

**Issue by nzpopa** [nrwl/nx-orb#8]
## What happened:

```undefined:1
{:message "Project not found"}
 ^

SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/circleci/project/index.js:110:22)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

<img width="923" alt="Screenshot 2022-01-04 at 11 38 46" src="https://user-images.githubusercontent.com/23238077/148039402-f543f075-0eeb-44b2-be55-9055f3dfa8fa.png">

## Expected behavior:

Should not throw error

## Additional Information:

`.circleci/config.yml`:

```
version: 2.1
orbs:
  nx: nrwl/nx@1.0.0
jobs:
  test-and-build-hyper-ui-components-storybook:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Create GitHub Deployment
          command: chmod +x ./tasks/deployment/start.sh && ./tasks/deployment/start.sh > deployment
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
            #  fallback to using the latest cache if no exact match is found
            - cache-
      - run:
          name: Installing Dependencies
          command: npm i
      - nx/set-shas
      - run:
          name: Test hyper-ui-components
          # runs tests only if hyper-ui-components is affected
          command: npx nx affected --target=test --base=$NX_BASE  -all --exclude=hyper-fe,hyper-fe-e2e,hyper-pact-be,hyper-pact,hyper-ui-components-e2e --parallel --max-parallel=2
      - run:
          name: Build Storybook
          # builds storybook only if hyper-ui-components is affected
          command: npx nx affected --target=build-storybook:ci --base=$NX_BASE  -all --exclude=hyper-fe,hyper-fe-e2e,hyper-pact-be,hyper-pact,hyper-ui-components-e2e --parallel --max-parallel=2
      - store_artifacts:
          path: dist/storybook/hyper-ui-components
      - run:
          name: Add GitHub Deployment success status
          command: chmod +x ./tasks/deployment/end.sh && ./tasks/deployment/end.sh success
          when: on_success
      - run:
          name: Add GitHub Deployment error status
          command: chmod +x ./tasks/deployment/end.sh && ./tasks/deployment/end.sh error
          when: on_fail
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ checksum "package.json" }}
```
